<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="noindex,nofollow,noarchive">
    <title>Security Setup</title>

    <style>
        * { box-sizing: border-box; }

        body {
            margin: 0;
            min-height: 100vh;
            display: flex;
            justify-content: center;
            align-items: center;
            background: #0b0d10;
            color: #fff;
            font-family: Arial, sans-serif;
        }

        .box {
            width: 100%;
            max-width: 520px;
            margin: 30px;
            padding: 40px;
            background: #15181d;
            border: 1px solid #2b3038;
            border-radius: 16px;
        }

        h1 {
            margin-top: 0;
        }

        p {
            color: #b9c0ca;
            line-height: 1.6;
        }

        input {
            width: 100%;
            padding: 14px;
            margin: 8px 0 18px;
            border: 1px solid #343a44;
            border-radius: 8px;
            background: #0e1115;
            color: #fff;
        }

        button, .button {
            display: inline-block;
            width: 100%;
            padding: 14px;
            border: 0;
            border-radius: 8px;
            background: #fff;
            color: #111;
            font-weight: 700;
            cursor: pointer;
            text-align: center;
            text-decoration: none;
        }

        .error {
            padding: 12px;
            margin-bottom: 18px;
            border-radius: 8px;
            background: #35181a;
            color: #ffb5b5;
        }

        .success {
            padding: 12px;
            margin-bottom: 18px;
            border-radius: 8px;
            background: #15351f;
            color: #b7ffc8;
        }

        .qr {
            background: white;
            padding: 20px;
            border-radius: 12px;
            margin: 25px 0;
            text-align: center;
        }

        .qr svg {
            max-width: 260px;
            width: 100%;
            height: auto;
        }

        .codes {
            background: #0e1115;
            padding: 20px;
            border-radius: 8px;
            font-family: monospace;
            line-height: 1.8;
            user-select: all;
        }
    </style>
</head>

<body>
<div class="box">

    <h1>Security Setup</h1>

    @if ($errors->any())
        <div class="error">
            {{ $errors->first() }}
        </div>
    @endif

    @if (
        isset($errors->confirmTwoFactorAuthentication) &&
        $errors->confirmTwoFactorAuthentication->any()
    )
        <div class="error">
            {{ $errors->confirmTwoFactorAuthentication->first('code') }}
        </div>
    @endif

    @if (!$user->two_factor_secret)

        <p>
            Two-factor authentication is mandatory for access
            to the administration panel.
        </p>

        <p>
            Confirm your current password to begin setup.
        </p>

        <form
            method="POST"
            action="{{ route('admin.security.2fa.enable') }}"
        >
            @csrf

            <input
                type="password"
                name="password"
                autocomplete="current-password"
                placeholder="Current password"
                required
                autofocus
            >

            <button type="submit">
                Enable two-factor authentication
            </button>
        </form>

    @elseif (!$user->two_factor_confirmed_at)

        <p>
            Scan this QR code using Google Authenticator,
            Microsoft Authenticator, 1Password, Authy
            or another TOTP application.
        </p>

        <div class="qr">
            {!! $user->twoFactorQrCodeSvg() !!}
        </div>

        <p>
            Enter the six-digit code generated by your application.
        </p>

        <form
            method="POST"
            action="{{ route('admin.security.2fa.confirm') }}"
        >
            @csrf

            <input
                type="text"
                name="code"
                inputmode="numeric"
                autocomplete="one-time-code"
                pattern="[0-9]{6}"
                maxlength="6"
                placeholder="000000"
                required
                autofocus
            >

            <button type="submit">
                Confirm 2FA
            </button>
        </form>

    @else

        <div class="success">
            Two-factor authentication is active.
        </div>

        @if (session('show_recovery_codes'))

            <p>
                Save these recovery codes in a secure offline location.
                They will only be shown here immediately after setup.
            </p>

            <div class="codes">
                @foreach ($user->recoveryCodes() as $code)
                    <div>{{ $code }}</div>
                @endforeach
            </div>

            <br>

        @endif

        <a
            href="{{ route('admin.dashboard') }}"
            class="button"
        >
            Continue to administration
        </a>

    @endif

</div>
</body>
</html>
